### ISSUE TITLE
Unable to build properly with `react-native link`

### ISSUE THREAD

**Issue by sonaye** [expo/expo-local-authentication#1]
Building a non-expo (regular react native app) on iOS after running `react-native link expo-local-authentication` throws with the error:

```bash
clang: error: no such file or directory: '~/node_modules/expo-local-authentication/ios/EXFingerprint/EXFingerprint.m'
```

The file `EXFingerprint.m` seems to be missing. It's my understanding thta this should work as a universal module outside of Expo.

**Comment by sjchmiela** [comment]
Hey, @sonaye! Unfortunately `react-native link` doesn't support universal modules. Moreover, although in the READMEs we mention possibility of installation without Cocoapods, it isn't supported either.

To use universal modules outside of Expo you'll need to do a couple of things:
- install [`expo-core`](https://github.com/expo/expo/tree/master/packages/expo-core#expo-core) — this is the package that lets universal modules be really universal, i. e. it is platform-independent, lets modules talk to each other, etc.
- install [`expo-react-native-adapter`](https://github.com/expo/expo/tree/master/packages/expo-react-native-adapter#expo-react-native-adapter) (do not forget about a few steps of [additional setup](https://github.com/expo/expo/tree/master/packages/expo-react-native-adapter#additional-required-setup)) — this package bridges universal world and React Native world, exports universal modules to JS
- install `expo-local-authentication` — install the package, add the dependency to `Podfile`

    ```ruby
    pod 'EXLocalAuthentication', path: '../node_modules/expo-local-authentication/ios'
    ```
    et voilà!

If you have any more questions, feel free to follow up, I'll be happy to answer all of them! 🙂

**Comment by sonaye** [comment]
Thanks for the detailed response, unfortunately using Cocoapods is not an option, we made a decision not to use it from the beginning. I had assumed that these modules are fully decoupled from Expo and can be used outside it, do you have any plans to support `react-native link`?

**Comment by sjchmiela** [comment]
Starting replying from the end:
- yes, these modules are fully decoupled from Expo and can be used outside of it. However note, that not only they are decoupled from Expo, they are also decoupled from React Native! (This `expo-local-authentication` module could also be used in eg. Flutter, using specific platform adapter.) That’s why `react-native link` isn’t working out of the box with these modules — it is designed for RN modules, and this isn’t one.
    
    If you’d like to know more about universal modules, I recently gave a talk at React Native EU where I tried to explain this concept and its architecture. Check it out at https://youtu.be/-9CJZRv7uOY.
- When it comes to Cocoapods vs no-Cocoapods… we currently don't support the Xcodeproj installation and there are no plans to do so. This decision comes from the process in which Expo develops its codebase — the main project has many dependencies and we use Cocoapods for consistency and easy dep management. And once you develop a library using Cocoapods, you tend not to use the Xcodeproj and it becomes outdated (for Cocoapods files are specified with a [glob](https://github.com/expo/expo-local-authentication/blob/master/ios/EXLocalAuthentication.podspec#L15), not specific filenames and the glob captures all the required files when running `pod install`).
    
    If you wanted to, you could clone the [`expo/expo`](https://github.com/expo/expo), open the `packages/expo-local-authentication/ios/EXLocalAuthentication.xcodeproj` and change all `EXFingerprint` references to `EXLocalAuthentication`. Then, you'd have to check whether `EXCore` and `EXReactNativeAdapter` projects are up to date, and then I encourage you to submit a pull request! 🙂
